name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: accuknox
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy: 
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      id: install  
      
    - name: Update kube config
      env:
        CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
      run: aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }}

    - name: Substitute variables in YAML files
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      run: |
        for file in wisecow-deployment.yml  wisecow-ingress.yml; do
          envsubst < $file > temp_$file
          mv temp_$file $file
        done     

    - name: Deploy to EKS
      run: |
       kubectl apply -f wisecow-deployment.yml
       kubectl apply -f service.yml
       kubectl apply -f wisecow-ingress.yml
